# docker build -t ottwatch-dev .

# docker run -t -i -p 80:80 ottwatch-dev
# docker run -t -i ottwatch-dev

FROM ubuntu:latest

RUN apt-get update && \
 apt-get -y install rails

RUN gem install rails

