# docker build -t ottwatch-dev .

# docker run -t -i -p 80:80 ottwatch-dev
# docker run -t -i ottwatch-dev

FROM ubuntu:20.04

RUN apt-get update && \
 apt-get -y install rails ruby-dev

RUN gem install rails

